version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend1:
    build: ./backend
    container_name: backend1
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"] # Add a health endpoint in your backend
      interval: 30s
      timeout: 10s
      retries: 3

  backend2:
    build: ./backend
    container_name: backend2
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    ports:
      - "5002:5000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend3:
    build: ./backend
    container_name: backend3
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    ports:
      - "5003:5000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy
      backend3:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - nginx

volumes:
  mongo-data: